<a href="https://colab.research.google.com/github/rishyg20/Alpha-Research---Assignment-2/blob/main/Alpha_Research_Assignment2_Pushkal_Rishabh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Alpha Research — Assignment 2
### Team: Pushkal & Rishabh

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import yfinance as yf
from datetime import datetime, timedelta
import time
import os
import requests

from google.colab import drive

drive.mount('/content/drive')
DATA_PATH = '/content/drive/MyDrive/AlphaResearch_Assignment2/data/raw/'

Mounted at /content/drive

## Section 2: S&P 500 Constituents

In [5]:
start = time.time()
header = {'User-Agent': 'Chrome'}
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
response = requests.get(url, headers= header)
tables = pd.read_html(response.text)
sp500 = tables[0]

today = datetime.today().strftime("%Y-%m-%d")
sp500['download_date'] = today
print(sp500.shape)
print(sp500.head())
display(sp500)
os.makedirs(DATA_PATH, exist_ok = True)
sp500.to_csv(DATA_PATH + f"sp500_constituents_{today}.csv", index = False)
end = time.time()
print(f"Time taken: {round(end - start,2)} seconds")

(503, 9)
  Symbol             Security             GICS Sector  \
0    MMM                   3M             Industrials
1    AOS          A. O. Smith             Industrials
2    ABT  Abbott Laboratories             Health Care
3   ABBV               AbbVie             Health Care
4    ACN            Accenture  Information Technology

                GICS Sub-Industry    Headquarters Location  Date added  \
0        Industrial Conglomerates    Saint Paul, Minnesota  1957-03-04
1               Building Products     Milwaukee, Wisconsin  2017-07-26
2           Health Care Equipment  North Chicago, Illinois  1957-03-04
3                   Biotechnology  North Chicago, Illinois  2012-12-31
4  IT Consulting & Other Services          Dublin, Ireland  2011-07-06

       CIK      Founded download_date
0    66740         1902    2026-05-18
1    91142         1916    2026-05-18
2     1800         1888    2026-05-18
3  1551152  2013 (1888)    2026-05-18
4  1467373         1989    2026-05-18

/tmp/ipykernel_14935/4023875586.py:5: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded,download_date
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902,2026-05-18
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916,2026-05-18
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888,2026-05-18
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888),2026-05-18
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989,2026-05-18
...,...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011,2026-05-18
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997,2026-05-18
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969,2026-05-18
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927,2026-05-18
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952,2026-05-18

Time taken: 2.82 seconds

In [6]:
start = time.time()

stock_list = sp500['Symbol'].tolist()
end_date = datetime.today().strftime("%Y-%m-%d")
start_date = "2016-01-01"
#downloading Adj Stock price of SP500 constituents
prices = yf.download(stock_list, start = start_date, end = end_date, auto_adjust = True)
display(prices)
print(prices.shape)


end = time.time()
print(f"Time taken: {round(end - start,2)} seconds")
#yfinance drops Adj Close when auto_adjust=True — adjusted prices are stored under Close instead.

[*********************100%***********************]  503 of 503 completed
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['BRK.B']: YFTzMissingError('possibly delisted; no timezone found')
ERROR:yfinance:['BF.B']: YFPricesMissingError('possibly delisted; no price data found  (1d 2016-01-01 -> 2026-05-18)')

Price      Adj Close             Close                                      \
Ticker          BF.B BRK.B           A        AAPL        ABBV        ABNB
Date
2016-01-04       NaN   NaN   37.483685   23.709106   37.397282         NaN
2016-01-05       NaN   NaN   37.354710   23.114973   37.241467         NaN
2016-01-06       NaN   NaN   37.520542   22.662617   37.247974         NaN
2016-01-07       NaN   NaN   35.926857   21.706152   37.137623         NaN
2016-01-08       NaN   NaN   35.549168   21.820929   36.124950         NaN
...              ...   ...         ...         ...         ...         ...
2026-05-11       NaN   NaN  111.459999  292.679993  202.779999  137.050003
2026-05-12       NaN   NaN  112.900002  294.799988  207.860001  135.479996
2026-05-13       NaN   NaN  112.739998  298.869995  208.500000  132.970001
2026-05-14       NaN   NaN  113.260002  298.209991  210.770004  133.669998
2026-05-15       NaN   NaN  111.699997  300.230011  210.389999  132.850006

Price                                                     ...   Volume  \
Ticker            ABT       ACGL         ACN        ADBE  ...       WY
Date                                                      ...
2016-01-04  35.159630  21.823122   86.213043   91.970001  ...  3556800
2016-01-05  35.151447  21.902363   86.661789   92.339996  ...  2722800
2016-01-06  34.856621  21.937229   86.492462   91.019997  ...  4843200
2016-01-07  34.021236  21.915041   83.952530   89.110001  ...  4917400
2016-01-08  33.308701  21.686827   83.139763   87.849998  ...  5022600
...               ...        ...         ...         ...  ...      ...
2026-05-11  82.559998  93.830002  172.350006  246.149994  ...  4902300
2026-05-12  84.349998  94.309998  169.770004  240.830002  ...  6219200
2026-05-13  83.830002  93.320000  159.639999  236.070007  ...  7638700
2026-05-14  84.900002  93.459999  163.990005  237.009995  ...  4360100
2026-05-15  84.470001  93.980003  168.820007  247.600006  ...  6414400

Price                                                                        \
Ticker         WYNN      XEL       XOM      XYL      XYZ       YUM      ZBH
Date
2016-01-04  4249800  2819300  20400100  1353400  2751500   4821623  2104084
2016-01-05  4286100  2141200  11993500  1075400  2352800   5273420  2294737
2016-01-06  3316100  5191900  18826900  1866000  1850600   5049330  2751233
2016-01-07  5525600  5212200  21263800  1555400  1636000  11005453  1829589
2016-01-08  5740000  3005400  19033600  1471500   587300   5996184  1670969
...             ...      ...       ...      ...      ...       ...      ...
2026-05-11  2717300  8070500  14849500  1669400  5319300   1858800  2229600
2026-05-12  1638900  9548100  16443100  1838600  6222300   1447100  2436500
2026-05-13  1555100  3867900  15772800  1987300  6467700   1701000  2239200
2026-05-14  2040700  4269500  11331500  1961000  5270800   1507100  2170800
2026-05-15  1028100  4701700  27864600  2303900  5106900   2156600  2578900

Price
Ticker         ZBRA       ZTS
Date
2016-01-04   656200   2871700
2016-01-05   611300   3116700
2016-01-06   881900   4670500
2016-01-07  1210600   4324400
2016-01-08  1034700   4946100
...             ...       ...
2026-05-11   971700  15641100
2026-05-12  2879400  18430100
2026-05-13  1392500  13085600
2026-05-14  1264600   8714800
2026-05-15  1224600   8944600

[2607 rows x 2517 columns]

(2607, 2517)
Time taken: 100.23 seconds

In [10]:
adj_close = prices['Close']
print(adj_close.shape)
print(adj_close.head())
adj_close.to_csv("DATA_PATH" + f"prices_close{today}.csv")
print(f"File saved for {adj_close.shape[1]} stocks, {adj_close.shape[0]} trading days")

(2607, 503)
Ticker              A       AAPL       ABBV  ABNB        ABT       ACGL  \
Date
2016-01-04  37.483685  23.709106  37.397282   NaN  35.159630  21.823122
2016-01-05  37.354710  23.114973  37.241467   NaN  35.151447  21.902363
2016-01-06  37.520542  22.662617  37.247974   NaN  34.856621  21.937229
2016-01-07  35.926857  21.706152  37.137623   NaN  34.021236  21.915041
2016-01-08  35.549168  21.820929  36.124950   NaN  33.308701  21.686827

Ticker            ACN       ADBE        ADI        ADM  ...         WY  \
Date                                                    ...
2016-01-04  86.213043  91.970001  44.534786  26.397753  ...  20.020790
2016-01-05  86.661789  92.339996  44.207565  26.692375  ...  20.067772
2016-01-06  86.492462  91.019997  42.326046  26.044210  ...  19.624805
2016-01-07  83.952530  89.110001  41.246227  25.425516  ...  18.899948
2016-01-08  83.139763  87.849998  40.886272  25.329762  ...  18.725443

Ticker           WYNN        XEL        XOM        XYL    XYZ        YUM  \
Date
2016-01-04  60.409386  26.027575  49.319614  31.806705  12.16  42.875278
2016-01-05  61.551342  26.290037  49.739849  31.797890  11.51  42.768417
2016-01-06  58.362663  26.567080  49.325985  31.401197  11.52  42.465599
2016-01-07  52.872482  26.669155  48.536461  30.590157  11.16  41.016823
2016-01-08  50.720341  26.377535  47.555923  30.299244  11.31  40.458691

Ticker            ZBH       ZBRA        ZTS
Date
2016-01-04  90.880081  66.489998  43.327370
2016-01-05  92.772491  64.820000  44.005646
2016-01-06  93.174179  62.230000  44.014812
2016-01-07  91.031822  59.410000  42.676590
2016-01-08  90.648003  59.250000  42.053310

[5 rows x 503 columns]
File saved for 503 stocks, 2607 trading days